-- Run this file in Supabase SQL Editor.
-- It creates the API schema used by historyBack and enables public image delivery.

create table if not exists roles (
  id bigint generated by default as identity primary key,
  role_name varchar(255) not null unique,
  view_access boolean default false,
  edit_access boolean default false,
  delete_access boolean default false,
  create_access boolean default false,
  status boolean default true,
  created_by varchar(255), updated_by varchar(255), created_user_id bigint,
  createdat timestamptz default now(), updatedat timestamptz default now()
);

create table if not exists users (
  id bigint generated by default as identity primary key,
  name varchar(255) not null, email varchar(255) not null unique, password varchar(255) not null,
  phonenumber varchar(255), image varchar(255), role_id bigint default 2, role bigint,
  status boolean default true, user_verify varchar(30) default 'not verified', last_token varchar(255),
  created_by bigint, updated_by bigint, createdat timestamptz default now(), updatedat timestamptz default now()
);

create table if not exists product_categories (
  id bigint generated by default as identity primary key, title varchar(255) not null, description text,
  image varchar(255), status boolean default true, created_by bigint, updated_by bigint,
  createdat timestamptz default now(), updatedat timestamptz default now()
);

create table if not exists products (
  id bigint generated by default as identity primary key, title varchar(255) not null, description text,
  price numeric(10,2) not null default 0, image varchar(255), badge varchar(255), link varchar(255),
  categoryid bigint, status boolean default true, created_by bigint, updated_by bigint,
  createdat timestamptz default now(), updatedat timestamptz default now()
);

create table if not exists program (
  id bigint generated by default as identity primary key, title varchar(255) not null, description text,
  date timestamptz, location varchar(255), link varchar(255), image varchar(255), isfeatured boolean default false,
  isupcoming boolean default false, availabledates varchar(255), sessions varchar(255), duration varchar(255),
  participants varchar(255), modules varchar(255), status boolean default true, createdby bigint, updatedby bigint,
  createdat timestamptz default now(), updatedat timestamptz default now()
);

create table if not exists peoples (
  id bigint generated by default as identity primary key, name varchar(255) not null, title varchar(255), description text,
  mobile varchar(50), email varchar(255), social_links text, image varchar(255), role_id bigint, status boolean default true,
  created_by bigint, updated_by bigint, createdat timestamptz default now(), updatedat timestamptz default now()
);

create table if not exists district (
  id bigint generated by default as identity primary key, name varchar(255) not null, path text, centerx real, centery real,
  description text, images text, notableplaces text, status boolean default true, created_by bigint, updated_by bigint,
  createdat timestamptz default now(), updatedat timestamptz default now()
);

create table if not exists archaeological_sites (
  id bigint generated by default as identity primary key, name varchar(255) not null,
  type varchar(20) default 'cultural', description text, period varchar(255), image varchar(255), images text,
  districtid bigint, status boolean default true, created_by bigint, updated_by bigint,
  createdat timestamptz default now(), updatedat timestamptz default now()
);

create table if not exists contact_form (
  id bigint generated by default as identity primary key, name varchar(255), reciever_email varchar(255), sender_email varchar(255),
  subject varchar(255), message text, isreplied boolean default false, repliedmessage text, replydate timestamptz,
  status boolean default true, created_by bigint, updated_by bigint, createdat timestamptz default now(), updatedat timestamptz default now()
);

create table if not exists email_template (
  id bigint generated by default as identity primary key, name varchar(255), subject varchar(255), body text,
  status boolean default true, created_by bigint, updated_by bigint, createdat timestamptz default now(), updatedat timestamptz default now()
);

insert into roles (role_name, view_access, edit_access, delete_access, create_access)
values ('admin', true, true, true, true), ('moderator', true, true, false, true), ('user', true, false, false, false)
on conflict (role_name) do update set status = true;

insert into storage.buckets (id, name, public)
values ('uploads', 'uploads', true)
on conflict (id) do update set public = true;

create policy "Public can read uploads" on storage.objects for select using (bucket_id = 'uploads');
create policy "Authenticated users can upload" on storage.objects for insert to authenticated with check (bucket_id = 'uploads');
create policy "Authenticated users can update uploads" on storage.objects for update to authenticated using (bucket_id = 'uploads');
